# railway.toml

[build]
  # Perintah build yang dijalankan Railway untuk membangun aplikasi kamu
  command = "npm install"

[deploy]
  # Perintah start yang Railway jalankan untuk menjalankan server kamu
  command = "npm start"

[env]
  # Contoh environment variables yang kamu pakai di project
  PORT = "1031"
  MYSQL_PUBLIC_URL = "mysql://root:bZZiVdltNIAXBQaulfhyhlWeSkErQTOj@caboose.proxy.rlwy.net:44451/railway"
